### ISSUE TITLE
Pull in `felt` ui-style.css

### ISSUE THREAD

**Issue by greatbacon** [feltcoop/felt-server#56]
Now that Ryan has fleshed out a first pass on a styling css & theming; we should import it into `felt-server` and start adding it.

**Comment by ryanatkn** [comment]
To use this, we're adding this line to `src/routes/__layout.svelte`:

`import '@feltcoop/felt/ui/style.css';`

And if you need document-formatted text and other content:

`import '@feltcoop/felt/ui/Markup.svelte';`

and then:

`<Markup><p>some formatted text</p></Markup>
